Integrating Firebase
lukesno/seng-559 pull request #14
Opened 2024-03-12 09:16 UTC by lukesno

Changes:

"questions" array in "game" object contains id for question objects. This had to be done as Firestore does not support nested arrays (arrays inside arrays)

2024-03-12 17:20 UTC, TomAltankhuyag submitted a review, later dismissed

2024-03-12 17:29 UTC, ttran1017 commented on backend/process/src/http/routes.js
>    games[roomID] = newGame;
Can probably remove games object all together

2024-03-12 17:34 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +      questions[game.round * 2 + game.questionIndex]
nit: potentially replace the 2 here with some named constant (e.g. NUM_QUESTION_PER_ROUND)

2024-03-12 17:37 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +      questions[game.round * 2 + game.questionIndex].answers
same as above

2024-03-12 17:40 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +      questions[game.round * 2 + game.questionIndex].answers
```suggestion
      same as above
```

2024-03-12 17:41 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +    }
can maybe move to function since used in multiple places

2024-03-12 17:42 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +      questions[game.round * 2 + game.questionIndex].answers
same as above

2024-03-12 17:42 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +      if (game.questionIndex !== 2) {
replace 2 here

2024-03-12 17:44 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +        console.log("Hi")
Hi

2024-03-12 17:50 UTC, ttran1017 commented on backend/process/src/socket/socket.js
> +        console.log("Hi")
lol

2024-03-13 07:23 UTC, ttran1017 reviewed
Idea to maintain state on the processes and to update firestore asynchronously as state changes so we don't have latency problems. Then we can just read from the database to recover

2024-03-14 08:10 UTC, ttran1017 requested changes
Let's merge this instead https://github.com/lukesno/seng-559/pull/17

2024-04-10 03:40 UTC, closed without merging